// ── Per-route head metadata for the public pages (2026-07-30) ────────────────
//
// Every route used to share one <title>TrueCairn</title> from index.html, with
// no description, canonical or Open Graph tags at all — so a shared link
// rendered as a bare URL and every page competed with every other for the same
// title in a search result.
//
// A DATA TABLE, NOT JSX, ON PURPOSE. Two consumers need this: usePageMeta()
// sets it at runtime for browsers, and the build-time prerenderer writes it into
// the static HTML for crawlers that never run JavaScript. If the copy lived in
// each component, only the first consumer could reach it.
//
// CSP. apps/api/src/app.ts serves the SPA with `script-src 'self'
// 'wasm-unsafe-eval'; style-src 'self'` — no 'unsafe-inline'. Setting head tags
// imperatively through the DOM is unaffected by that (it is not inline script),
// and JSON-LD is unaffected too: a <script type="application/ld+json"> is a data
// block the HTML spec never prepares as executable script, so script-src has
// nothing to block. Both were verified in Chromium under the exact production
// policy before this shipped, rather than assumed either way. NO CSP CHANGE WAS
// MADE OR IS NEEDED.
//
// DESCRIPTIONS ARE WRITTEN FROM THE PAGES THEMSELVES, not generated. Where a
// page's own opening paragraph says the thing best, this paraphrases it closely.
// If a page ever exists whose content cannot support an honest description, omit
// it rather than pad — an absent description lets the search engine pick a
// snippet from the page, which is better than a confident sentence that misleads.

// The lastmod sidecar, GENERATED by scripts/sitemap.mjs alongside sitemap.xml.
// Imported rather than duplicated so `dateModified` in JSON-LD and `<lastmod>`
// in the sitemap are the same number from the same source. Build dates were
// rejected for both — see the long note in scripts/sitemap.mjs: a build date
// says every page changed every deploy, which is worse than saying nothing.
import i18next from 'i18next';
import {
  DEFAULT_LOCALE,
  SOURCE_LANGUAGE_ONLY_ROUTES,
  localesForRoute,
  localizePath,
  type Locale,
} from '@truecairn/shared';
import lastmodSidecar from '../../../../scripts/sitemap-lastmod.json';
import { PERSONAL_PRICE } from '../billing/pricing.js';
import { REPO_URL } from './links.js';

export const SITE_ORIGIN = 'https://truecairn.app';

// One shared social card. The landing hero poster is the only image we have that
// represents the product rather than a specific screen, and reusing an existing
// asset keeps this from inventing artwork nobody designed.
const DEFAULT_OG_IMAGE = '/assets/landing/hero-poster.jpg';

export interface PageMeta {
  // The catalog key stem: `site.meta.<stem>.title` and `.description`.
  stem: string;
  // 140–160 chars. Absent only if the page cannot support an honest one — an
  // absent description lets the search engine pick a snippet from the page,
  // which beats a confident sentence that misleads.
  hasDescription: boolean;
}

// Keyed by pathname. Exactly the routes in PUBLIC_CLIENT_ROUTES
// (apps/api/src/spa-routes.ts) — kept in step by page-meta.test.ts.
//
// THE WORDS MOVED TO THE CATALOG in Phase 2 (i18n/catalog/site/en.ts); this
// table keeps what it is actually authoritative about — which routes exist, and
// what shape their structured data takes. Splitting it that way is what lets a
// title be translated without this file growing a second copy of every string.
export const PAGE_META: Readonly<Record<string, PageMeta>> = {
  '/': { stem: 'home', hasDescription: true },
  '/guide': { stem: 'guide', hasDescription: true },
  '/changelog': { stem: 'changelog', hasDescription: true },
  '/status': { stem: 'status', hasDescription: true },
  '/security': { stem: 'security', hasDescription: true },
  '/security/threat-model': { stem: 'security.threatModel', hasDescription: true },
  '/security/ai': { stem: 'security.ai', hasDescription: true },
  '/security/build': { stem: 'security.build', hasDescription: true },
  '/security/limits': { stem: 'security.limits', hasDescription: true },
  '/security/disclosure': { stem: 'security.disclosure', hasDescription: true },
  '/legal/privacy': { stem: 'legal.privacy', hasDescription: true },
  '/legal/terms': { stem: 'legal.terms', hasDescription: true },
  '/legal/dpa': { stem: 'legal.dpa', hasDescription: true },
  '/legal/sub-processors': { stem: 'legal.subProcessors', hasDescription: true },
  '/legal/wind-down': { stem: 'legal.windDown', hasDescription: true },
  '/company/about': { stem: 'company.about', hasDescription: true },
  '/company/contact': { stem: 'company.contact', hasDescription: true },
  '/company/press': { stem: 'company.press', hasDescription: true },
};

// `lng` is passed explicitly rather than read from i18next's ambient language:
// the prerenderer emits hreflang alternates for languages it is not currently
// rendering in, and a helper that silently used the ambient one would produce a
// page whose alternates all pointed at itself.
export { localesForRoute, SOURCE_LANGUAGE_ONLY_ROUTES };

export function titleFor(route: string, locale: Locale): string {
  const meta = PAGE_META[route];
  if (meta === undefined) return 'Truecairn';
  return i18next.t(`site.meta.${meta.stem}.title` as never, { lng: locale });
}

export function descriptionFor(route: string, locale: Locale): string | undefined {
  const meta = PAGE_META[route];
  if (meta === undefined || !meta.hasDescription) return undefined;
  return i18next.t(`site.meta.${meta.stem}.description` as never, { lng: locale });
}

// ── Structured data ─────────────────────────────────────────────────────────
//
// EVERY FIELD IS A FACT ALREADY STATED ON A PUBLIC PAGE. Structured data that
// overclaims is the same failure as a status page inventing an uptime figure —
// except a search engine repeats it for you, to people who never visited. If a
// field cannot be pointed at a sentence on a page, it is omitted rather than
// guessed. That rule is why there is no aggregateRating, no award, no employee
// count and no certification here, and why sameAs holds exactly one entry.
//
// EMITTED FOR EVERY ROUTE, from the same table the prerenderer reads. Both
// consumers — usePageMeta() at runtime and prerender.tsx at build time — call
// jsonLdFor(), so a crawler that never runs JS and a browser that does cannot
// see different structured data. That symmetry is the whole design of this
// module; anything that emits JSON-LD from only one side breaks it.

const ORG_DESCRIPTION =
  'Truecairn is a zero-knowledge digital continuity platform: owners encrypt their most important information on their own devices, and people they chose can reconstruct access through consensus if they go silent.';

type JsonLdNode = Record<string, unknown>;

// A route is "nested" when it has a parent section — /security/*, /legal/*,
// /company/*. Derived from the path rather than listed, so a new nested page
// gets a breadcrumb by existing.
function isNested(route: string): boolean {
  return route.split('/').length === 3;
}

// The breadcrumb leaf. Every title in the table is either "Short name — qualifier"
// or already short ("How Truecairn uses AI"), so taking the part before the dash
// keeps the label sourced from the table instead of invented alongside it.
function leafName(title: string): string {
  return title.split(' — ')[0] ?? title;
}

interface LastmodSidecar {
  routes: Record<string, { lastmod?: string } | undefined>;
}

// A route with no sidecar entry gets NO dateModified. An absent date is read as
// "unknown"; a wrong one is believed — the same asymmetry that governs the
// canonical and description rules above.
function dateModifiedFor(route: string): string | undefined {
  return (lastmodSidecar as LastmodSidecar).routes[route]?.lastmod;
}

function organizationNode(): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Truecairn',
    // NO legalName. It read 'Truecairn, Inc.' until 2026-08-13, for a company
    // that has never been incorporated — and this is the field with the widest
    // reach of the six that carried it, because a search engine repeats it
    // verbatim and it shipped in the prerendered HTML of all 17 public pages.
    // Omitting a field is not a claim; a wrong one is. The same asymmetry
    // governs `description` and `dateModified` above, and it is why the fix is
    // deletion rather than a substitute: there is no legal name to put here
    // until the entity decision in docs/31 §1 is made.
    url: SITE_ORIGIN,
    logo: `${SITE_ORIGIN}/assets/brand/mark.svg`,
    description: ORG_DESCRIPTION,
    email: 'hello@truecairn.app',
    // The public source repository, linked in the footer and required by
    // /security/build's rebuild-and-compare instructions. ONE entry because
    // there is exactly one real profile: padding sameAs with accounts that do
    // not exist is how a machine-readable claim becomes a lie. Degrades to no
    // sameAs at all if REPO_URL is ever unset, exactly as the footer does.
    ...(REPO_URL !== null ? { sameAs: [REPO_URL] } : {}),
  };
}

function webSiteNode(): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'Truecairn',
    url: SITE_ORIGIN,
  };
}

// The product itself. Offers mirror the pricing section of the landing page
// EXACTLY, read from the same constants that render it (billing/pricing.ts), so
// a price change cannot leave a stale figure in the markup search engines quote.
//
// Both paid offers are listed because the page sells both behind its
// monthly/yearly switch. The headline "$6.67 / month" a visitor sees on the
// annual option is deliberately NOT here: it is the annual total divided by
// twelve for display, and nobody is ever charged it. Structured data carries the
// amounts that are actually billed — $8 monthly, $80 annually — with the period
// named in the offer, because Offer.price has no period of its own.
function softwareApplicationNode(): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'Truecairn',
    applicationCategory: 'SecurityApplication',
    // Stated all over the public pages: the encrypting code runs in the browser
    // (/security, /security/build).
    operatingSystem: 'Web browser',
    url: SITE_ORIGIN,
    description: ORG_DESCRIPTION,
    offers: [
      {
        '@type': 'Offer',
        name: 'Free',
        price: '0',
        priceCurrency: 'USD',
      },
      {
        '@type': 'Offer',
        name: 'Personal, billed monthly',
        price: String(PERSONAL_PRICE.monthlyPerMonth),
        priceCurrency: 'USD',
      },
      {
        '@type': 'Offer',
        name: 'Personal, billed annually',
        price: String(PERSONAL_PRICE.annualPerYear),
        priceCurrency: 'USD',
      },
    ],
  };
}

function breadcrumbNode(route: string, locale: Locale): JsonLdNode {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    // Two levels: the site root, then the page. Deliberately NOT three — there
    // is no /security or /legal index page for every section (/legal is a 404),
    // so naming a middle crumb would put a URL that does not exist into markup
    // a crawler follows.
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Truecairn', item: SITE_ORIGIN },
      {
        '@type': 'ListItem',
        position: 2,
        name: leafName(titleFor(route, locale)),
        item: canonicalFor(route, locale),
      },
    ],
  };
}

function webPageNode(route: string, locale: Locale): JsonLdNode {
  const dateModified = dateModifiedFor(route);
  const description = descriptionFor(route, locale);
  return {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: titleFor(route, locale),
    url: canonicalFor(route, locale),
    ...(description !== undefined ? { description } : {}),
    ...(dateModified !== undefined ? { dateModified } : {}),
    isPartOf: { '@type': 'WebSite', name: 'Truecairn', url: SITE_ORIGIN },
  };
}

/**
 * The JSON-LD for a public route, or `undefined` for anything not in the table
 * (a 404 must not describe itself as a page that exists).
 */
export function jsonLdFor(route: string, locale: Locale = DEFAULT_LOCALE): string | undefined {
  const meta = PAGE_META[route];
  if (meta === undefined) return undefined;
  const nodes: JsonLdNode[] = [];
  // Organization, WebSite and the product go on the landing page only: they
  // describe the site as a whole, and repeating them per page would have a
  // crawler reconcile seventeen copies of the same entity.
  if (route === '/') nodes.push(organizationNode(), webSiteNode(), softwareApplicationNode());
  if (isNested(route)) nodes.push(breadcrumbNode(route, locale));
  nodes.push(webPageNode(route, locale));
  return JSON.stringify(nodes);
}

// The canonical URL for a route IN A GIVEN LANGUAGE. The default language keeps
// the bare path it already publishes — /security, never /en/security — because
// those URLs are indexed and linked, and moving them would break every inbound
// link to buy nothing.
export function canonicalFor(pathname: string, locale: Locale = DEFAULT_LOCALE): string {
  return `${SITE_ORIGIN}${localizePath(pathname, locale)}`;
}

export function ogImageFor(): string {
  return `${SITE_ORIGIN}${DEFAULT_OG_IMAGE}`;
}
